services:
  nfld-frontend:
    image: nfld-frontend
    container_name: nfld-frontend
    restart: unless-stopped
    ports:
      - 8888:80
    environment:
      - TZ=America/Chicago
    labels:
      - wud.watch=false
      - dockge.imageupdates.check=false
      - homepage.group=Personal
      - homepage.name=NFLd
      - homepage.icon=https://nfl.postfmly.com/favicon.png
      - homepage.href=https://nfl.postfmly.com/
      - homepage.description=nfl.postfmly.com
  nfld-backend:
    image: nfld-backend
    container_name: nfld-backend
    restart: unless-stopped
    ports:
      - 5555:5555
    stop_signal: SIGINT
    labels:
      - wud.watch=false
      - dockge.imageupdates.check=false
  nginx:
    image: nfld-nginx
    container_name: nfld-nginx
    restart: unless-stopped
    ports:
      - 88:80
    depends_on:
      - nfld-backend
      - nfld-frontend
    labels:
      - wud.watch=false
      - dockge.imageupdates.check=false
networks: {}
x-dockge:
  urls:
    - https://nfl.postfmly.com
