services:
  frontend:
    image: nfld-frontend
    ports:
      - 88:80
    container_name: nfld-frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend
  backend:
    image: nfld-backend
    expose:
      - 5555:5555
    container_name: nfld-backend
    restart: unless-stopped
    volumes:
      - ./backend:/backend
    network_mode: host
