services:
  nfld-frontend:
    container_name: nfld-frontend
    image: git.postfmly.com/admin/nfld-frontend:arm64
    restart: unless-stopped
    depends_on:
      - nfld-backend
    ports:
      - "88:80"
    environment:
      - TZ=America/Chicago
    labels:
      - wud.display.name=NFLd (Frontend)
      - homepage.group=Personal
      - homepage.name=NFLd
      - homepage.icon=https://nfl.postfmly.com/nfld.png
      - homepage.href=https://nfl.postfmly.com/
      - homepage.description=nfl.postfmly.com
      - homepage.widget.type=customapi
      - homepage.widget.url=https://api.postfmly.com/nfld/kc/2025
      - homepage.widget.refreshInterval=60000
      - homepage.widget.mappings[0].field=team
      - homepage.widget.mappings[0].label=Team
      - homepage.widget.mappings[1].field=record
      - homepage.widget.mappings[1].label=Record

  nfld-backend:
    container_name: nfld-backend
    image: git.postfmly.com/admin/nfld-backend:arm64
    restart: unless-stopped
    ports:
      - "5555:5555"
    labels:
      - wud.display.name=NFLd (Backend)
    stop_signal: SIGINT

networks: {}

x-dockge:
  urls:
    - https://nfl.postfmly.com
