services:
  nfld-frontend:
    container_name: nfld-frontend
    image: nfld-frontend
    restart: unless-stopped
    depends_on:
      - nfld-backend
    ports:
      - '88:80'
    environment:
      - TZ=America/Chicago
    labels:
      - wud.watch=false
      - dockge.imageupdates.check=false
      - homepage.group=Personal
      - homepage.name=NFLd
      - homepage.icon=https://nfl.postfmly.com/favicon.png
      - homepage.href=https://nfl.postfmly.com/
      - homepage.description=nfl.postfmly.com
      - homepage.widget.type=customapi
      - homepage.widget.url=https://api.postfmly.com/nfld/kc
      - homepage.widget.refreshInterval=60000
      - homepage.widget.mappings[0].field=team
      - homepage.widget.mappings[0].label=Team
      - homepage.widget.mappings[1].field=record
      - homepage.widget.mappings[1].label=Record

  nfld-backend:
    container_name: nfld-backend
    image: nfld-backend
    restart: unless-stopped
    ports:
      - '5555:5555'
    labels:
      - wud.watch=false
      - dockge.imageupdates.check=false
    stop_signal: SIGINT
networks: {}

x-dockge:
  urls:
    - https://nfl.postfmly.com
