services:
  nfld-frontend:
    image: nfld-frontend
    container_name: nfld-frontend
    restart: unless-stopped
    ports:
      - 88:80
    depends_on:
      - nfld-backend
  nfld-backend:
    image: nfld-backend
    container_name: nfld-backend
    restart: unless-stopped
    ports:
      - 5555:5555
