services:
  nfld-frontend:
    image: nfld-frontend
    container_name: nfld-frontend
    restart: unless-stopped
    ports:
      - 8888:80
    labels:
      - wud.watch=false
      - dockge.imageupdates.check=false
  nfld-backend:
    image: nfld-backend
    container_name: nfld-backend
    restart: unless-stopped
    ports:
      - 5555:5555
    labels:
      - wud.watch=false
      - dockge.imageupdates.check=false
  nginx:
    image: nfld-nginx
    container_name: nfld-nginx
    restart: unless-stopped
    ports:
      - 88:80
    depends_on:
      - nfld-backend
      - nfld-frontend
    labels:
      - wud.watch=false
      - dockge.imageupdates.check=false
