[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "nfld-backend"
version = "1.0.0"
dependencies = [
    "flask",
    "flask-cors",
    "gunicorn",
    "requests",
    "requests_cache"
]
requires-python = ">= 3.11"

[project.optional-dependencies]
dev = [
    "behave",
    "pip-review",
    "pip3-autoremove",
    "pylint"
]
