[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "nfld"
version = "0.0.1"
dependencies = [
    "flask",
    "gunicorn",
    "requests",
    "requests_cache"
]
requires-python = ">= 3.11"

[project.optional-dependencies]
dev = [
    "pip-review",
    "pip3-autoremove",
    "pylint"
]
